services:
  postgres:
    image: postgres:16
    container_name: ruian-postgres
    environment:
      POSTGRES_DB: ruian
      POSTGRES_USER: ruian
      POSTGRES_PASSWORD: ruian
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
