CREATE TABLE IF NOT EXISTS obec (
    kod VARCHAR(20) PRIMARY KEY,
    nazev VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS cast_obce (
    kod VARCHAR(20) PRIMARY KEY,
    nazev VARCHAR(255) NOT NULL,
    kod_obce VARCHAR(20) NOT NULL REFERENCES obec(kod)
);
